:concurrency: 50
:queues:
  - reports_generator_job
  - launcher_job
  - ticker_fetcher_job
  - tickers_fetcher_job
:schedule:
  reports_generator_job:
    every: ['60s', first_in: '60s']   # Runs once per minute
    class: ReportsGeneratorJob
    # every: ['60s', first_in: '900s']   # Runs once per minute
  # launcher_job:
  #   in: '2s'
  #   class: LauncherJob
