:concurrency: 50
:queues:
  - ticker_fetcher_job
  - markets_fetcher_job
  - reports_generator_job
:schedule:
  markets_fetcher_job:
    every: ['30s', first_in: '2s']   # Runs once per minute
    class: MarketsFetcherJob
  reports_generator_job:
    every: ['30s', first_in: '27s']   # Runs once per minute
    class: ReportsGeneratorJob
